Add support to use array in `controller` param in config
rebing/graphql-laravel pull request #906
Opened 2022-03-04 14:57 UTC by viktorruskai

## Summary
- This PR contains a small feature where you can use an array in the config file. It will help your IDE navigate to the method you are using.

```php
return [
    'route' => [
        // The prefix for routes; do NOT use a leading slash!
        'prefix' => 'graphql',

        //  Normal format: 
        // 'controller' => GraphQLController::class . '@query',

        // Array format:
        'controller' => [GraphQLController::class, 'query'],
        ...
```

- In your IDE it should look like this:
<img width="1404" alt="Screenshot 2022-03-04 at 15 46 34" src="https://user-images.githubusercontent.com/9396295/156784366-cfb31a2d-6ce0-4d63-9751-9b2acae39f1a.png">

---

Type of change:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Misc. change (internal, infrastructure, maintenance, etc.)

Checklist:
- [ ] Existing tests have been adapted and/or new tests have been added
- [ ] Add a CHANGELOG.md entry
- [ ] Update the README.md
- [x] Code style has been fixed via `composer fix-style`

2022-04-11 08:16 UTC, viktorruskai commented
@mfn I updated the Pull request.

2022-05-05 09:12 UTC, mfn requested changes
LGTM!

Can you please:
- work in my feedback
- add an example for array syntax in the config itself, .e. g
  ```
          // The controller/method to use in GraphQL request.
          // Also supported array syntax: `[\Rebing\GraphQL\GraphQLController::class, 'query']`
          'controller' => \Rebing\GraphQL\GraphQLController::class . '@query',
  ```
- resolve the conflicts with master?

After that, I'm happy to merge the PR!

2022-05-05 09:12 UTC, mfn commented on README.md
> +    replace the existing one. (also supports `array` format)
```suggestion
    replace the existing one (also supports `array` format).
```

2022-05-05 09:12 UTC, mfn commented on src/routes.php
> +                if (\is_array($actions['uses']) && isset($actions['uses'][0], $actions['uses'][1])) {
```suggestion
                // Support array syntax: `[Some::class, 'method']`
                if (\is_array($actions['uses']) && isset($actions['uses'][0], $actions['uses'][1])) {
```

2022-05-05 09:12 UTC, mfn commented on src/routes.php
> +            if (\is_array($graphiqlConfig['controller']) && isset($graphiqlConfig['controller'][0], $graphiqlConfig['controller'][1])) {
```suggestion
            // Support array syntax: `[Some::class, 'method']`
            if (\is_array($graphiqlConfig['controller']) && isset($graphiqlConfig['controller'][0], $graphiqlConfig['controller'][1])) {
```

2022-05-05 09:30 UTC, viktorruskai commented
@mfn I implemented everything you mentioned.

2022-05-05 11:51 UTC, mfn commented
I guess we've to run `composer phpstan-baseline` to update the baseline; not sure what the appropriate code/phpdoc fix would be and I would be fine adding it to the baseline.

(note: I generated it locally but I can't push to your branch)

2022-05-05 13:41 UTC, viktorruskai commented
@mfn Yeah, sure ...  I updated the baseline. Also, I tried to set proper PHPDoc with [PHPStan Array Shape](https://phpstan.org/writing-php-code/phpdoc-types#array-shapes), but unsuccessfully.

2022-05-05 20:55 UTC, merged

2022-05-05 20:56 UTC, mfn commented
@viktorruskai thanks!

Unfortunately the baseline needs to be generated with the same PHP version running on GHA, which is 8.1 and not 7.4

I fixed this with https://github.com/rebing/graphql-laravel/pull/916 , which included your PR 🎉 

Thanks for your contribution!